FROM python:3.6-alpine

ENV CELERY_BROKER_URL redis://celery-redis.default.svc.cluster.local:6379/0
ENV CELERY_RESULT_BACKEND redis://celery-redis.default.svc.cluster.local:6379/0
ENV C_FORCE_ROOT true

COPY . /queue
WORKDIR /queue

RUN pip install -r requirements.txt

ENTRYPOINT flower -A tasks --port=5555 --broker=$CELERY_BROKER_URL
