apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: worker
  name: celery-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - image: teochenglim/celery-worker
        env:
        - name: CELERY_BROKER_URL
          value: "redis://celery-redis.default.svc.cluster.local:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://celery-redis.default.svc.cluster.local:6379/0"
        args:
        - -A
        - tasks
        - worker
        - --loglevel=info
        - --concurrency=50
        command:
        - celery
        name: worker
        resources:
          requests:
            cpu: "200m"
      restartPolicy: Always
